# Generated by Django 5.1.6 on 2025-04-09 07:18

from django.db import migrations

def copy_pagador_to_temp(apps, schema_editor):
    Gasto = apps.get_model('tasks', 'Gasto')
    for gasto in Gasto.objects.all():
        gasto.pagador_temp = gasto.pagador
        gasto.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_gasto_pagador_temp'),
    ]

    operations = [
        migrations.RunPython(copy_pagador_to_temp),
    ]
