# Generated by Django 5.1.6 on 2025-04-09 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20250409_0218'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='pagador',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='pagador_temp',
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagadores',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
