# Generated by Django 5.1.6 on 2025-04-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_gasto_pagador_remove_gasto_pagador_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='pagadores',
        ),
        migrations.AddField(
            model_name='gasto',
            name='numero_pagadores',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de pagadores'),
        ),
    ]
